#!/bin/bash
set -euo pipefail

# ============================================================
# generate.sh — Single-source rule generator
#
# Reads the canonical source of truth:
#   rules/core.md      (the 10 non-negotiable rules — weak-model optimized)
#   rules/extended.md  (full engineering depth)
#
# Produces IDE/agent-specific rule files into dist/, each assembled
# under one of three profiles:
#   minimal → only project-specific constraints (Anthropic Claude 原生模型 in Claude Code)
#   lean    → core inline + pointer to extended (非原生模型 in Claude Code, AGENTS.md, Copilot, Trae)
#   full    → core + extended fully inline      (Cursor, Windsurf, Cline)
#
# setup.sh symlinks the project-root rule files to dist/<file>, so a
# single edit to core.md / extended.md propagates everywhere after
# re-running this script.
#
# Usage:
#   ./generate.sh            # regenerate the default single entry: dist/AGENTS.md
#   ./generate.sh --all      # regenerate optional compatibility entries too
#   ./generate.sh --check    # verify default dist/AGENTS.md is up to date, no writes
#   ./generate.sh --check --all
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}ℹ️  $1${NC}"; }
ok()    { echo -e "${GREEN}✅ $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠️  $1${NC}"; }
fail()  { echo -e "${RED}❌ $1${NC}"; }

HARNESS_ROOT="$(cd "$(dirname "$0")" && pwd)"
CORE="$HARNESS_ROOT/rules/core.md"
EXTENDED="$HARNESS_ROOT/rules/extended.md"
DIST="$HARNESS_ROOT/dist"
CAPSULE_MAX_BYTES="${MICK_HARNESS_CAPSULE_MAX_BYTES:-4096}"

CHECK_MODE=false
GEN_ALL=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)
            CHECK_MODE=true
            shift
            ;;
        --all|--all-rules|--compat)
            GEN_ALL=true
            shift
            ;;
        -h|--help)
            echo "Usage: ./generate.sh [--check] [--all]"
            echo ""
            echo "Default: generate/check only dist/AGENTS.md."
            echo "Use --all for legacy tool-specific rule files."
            exit 0
            ;;
        *)
            fail "Unknown option: $1"
            exit 1
            ;;
    esac
done

for f in "$CORE" "$EXTENDED"; do
    if [ ! -f "$f" ]; then
        fail "Source of truth missing: $f"
        exit 1
    fi
done

# A short, machine-and-human readable "do not edit" banner.
banner() {
    cat <<EOF
<!-- ============================================================ -->
<!-- AUTO-GENERATED by .harness/generate.sh — DO NOT EDIT BY HAND -->
<!-- Edit the source of truth instead:                            -->
<!--   .harness/rules/core.md      (the 10 core rules)            -->
<!--   .harness/rules/extended.md  (full engineering rules)       -->
<!-- Then re-run: .harness/generate.sh                            -->
<!-- ============================================================ -->
EOF
}

# ----------------------------------------------------------------
# Personal Agent Capsule injection — connect the current user's private Brain.
#
# Public harness rules answer "how to work"; the private Brain answers
# "whose agent is this". If Brain is unavailable, this function emits
# nothing so fork users get a clean generic harness.
# ----------------------------------------------------------------
resolve_capsule_brain_dir() {
    local resolved=""
    if [ -f "$HARNESS_ROOT/scripts/brain-resolve.sh" ]; then
        # shellcheck disable=SC1091
        source "$HARNESS_ROOT/scripts/brain-resolve.sh"
        if resolve_brain_dir "$HARNESS_ROOT" >/dev/null 2>&1; then
            if [ "${BRAIN_MODE:-disabled}" = "disabled" ]; then
                echo ""
                return 0
            fi
            [ -n "${BRAIN_DIR:-}" ] && resolved="$BRAIN_DIR"
        fi
    fi

    if [ -z "$resolved" ]; then
        resolved="${HOME}/.brain"
    fi

    echo "$resolved"
}

emit_bounded_capsule() {
    local file="$1"
    python3 - "$file" "$CAPSULE_MAX_BYTES" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
limit = int(sys.argv[2])
raw = path.read_bytes()
if len(raw) <= limit:
    sys.stdout.write(raw.decode("utf-8"))
else:
    body = raw[:limit].decode("utf-8", errors="ignore").rstrip()
    sys.stdout.write(body + "\n\n> Capsule 已按常驻上下文预算截断；完整内容请按需读取 Brain 源文件。\n")
PY
}

agent_capsule_inject() {
    local brain_dir capsule constitution persona preferences collaboration gotchas
    brain_dir="$(resolve_capsule_brain_dir)"
    capsule="$brain_dir/global/agent-capsule.md"
    constitution="$brain_dir/constitution.md"
    persona="$brain_dir/global/persona.md"
    preferences="$brain_dir/global/preferences.md"
    collaboration="$brain_dir/global/collaboration-style.md"
    gotchas="$brain_dir/global/gotchas.md"

    has_meaningful_capsule_file() {
        local file="$1"
        [ -f "$file" ] || return 1
        awk '
            /^[[:space:]]*$/ { next }
            /^[[:space:]]*#/ { next }
            /^Record cross-project user preferences here\./ { next }
            /^Record cross-project pitfalls here\./ { next }
            /^<!--/ { next }
            { found=1 }
            END { exit(found ? 0 : 1) }
        ' "$file"
    }

    local has_capsule_source=false
    for f in "$capsule" "$constitution" "$persona" "$preferences" "$collaboration" "$gotchas"; do
        if has_meaningful_capsule_file "$f"; then
            has_capsule_source=true
            break
        fi
    done

    if [ "$has_capsule_source" != true ]; then
        return 0
    fi

    cat <<'INJECT_HEADER'

<!-- ============================================================ -->
<!-- Personal Agent Capsule — "There are many agent harnesses,    -->
<!-- but this one is mine."                                       -->
<!-- 来源: Brain constitution/persona/preferences/collaboration    -->
<!-- Brain 不存在时静默跳过，保留通用 Harness 行为。               -->
<!-- ============================================================ -->

## 🧬 Personal Agent Capsule（个人化 Harness 层）

> 目标：让 Coding Agent 读取当前用户私有 Brain 中的身份、偏好、协作方式和质量标准。公开 Harness 不内置任何个人画像，也不会把 Brain 正文复制进生成文件。

INJECT_HEADER

    if [ -f "$capsule" ]; then
        echo "> Capsule source: \`${capsule/#$HOME/~}\`"
        echo ""
        emit_bounded_capsule "$capsule"
    fi

    echo ""
    echo "**Capsule source files（存在即代表可进一步读取）**："
    for f in "$constitution" "$persona" "$preferences" "$collaboration" "$gotchas"; do
        if has_meaningful_capsule_file "$f"; then
            echo "- \`${f/#$HOME/~}\`"
        fi
    done

    if has_meaningful_capsule_file "$gotchas"; then
        echo ""
        echo "**Gotchas policy**：复杂任务、重复失败、macOS/工具链/多模型协作问题，先检索 Brain gotchas；不要默认把 gotchas 原文注入项目文件，避免私人上下文泄漏。"
    fi

    echo ""
    echo "---"
    echo ""
}

# Build one target file body to stdout.
#   $1 = profile (minimal|lean|full)
#   $2 = tool display name (for the intro line)
render() {
    local profile="$1" tool="$2"
    banner
    echo ""
    echo "# 工程规范 · $tool"
    echo ""

    # ⛔ Tripwire injected FIRST, before everything else — even the capsule.
    # Weak models that skim long files still hit these 3 lines.
    echo "## ⛔ 停手条件（违反任一条 = 立即停手）"
    echo ""
    echo "**1. 改动前必须先读。** 用 Read 工具读取要改的文件。凭记忆覆盖代码 = 违约。"
    echo "**2. 改动文件前先查 plan.md。** 用 \`ls\` 检查项目根目录的 \`plan.md\`。若存在且本轮要改动文件 → 按 plan 步骤执行，不改 plan 范围外的文件。纯解释、方向讨论、头脑风暴无需检查 plan。"
    echo "**3. 没验证 ≠ 完成。** 每条改动必须附带验证证据。禁止说\"应该好了 / 可以了 / 完成了\"。只能说\"已修改，待验证\"或\"已修改，验证通过：<命令> → <结果>\"。"
    echo ""

    agent_capsule_inject

    if [ "$profile" = "minimal" ]; then
        # Minimal profile: only rules the tool DOESN'T enforce natively.
        # For strong models (Claude Code) that already have built-in:
        #   - read before edit, plan before act, ask when unclear
        #   - defensive coding, error analysis, self-review
        #   - permission system for dangerous ops
        echo "> 本项目使用 Mick Harness。你的内建能力已覆盖大部分通用工程规范，以下补充 Mick 的个人 Agent Kernel 与项目级约束。"
        echo ""
        echo "## 项目级约束"
        echo ""
        echo "**⚡ 改动前检查 plan.md**：改动文件前先看 \`plan.md\`。存在且本轮要改动文件 → 按步骤执行。不存在 → 正常响应。"
        echo ""
        echo "**锁死技术栈**：不擅自更换语言/框架/库，不擅自引入新依赖。要换先说明原因并等用户确认。"
        echo ""
        echo "**回合卡片**：有交付物、正在推进 plan/workflow、多角色交接、发布/合并、长任务阶段更新、或出现卡点时，结尾输出回合卡片——✅ 本回合做了什么 / 🧠 是否做了深度推理 / 📍 整体进度 / ➡️ 下一步明确动作 / 🆘 有阻塞时卡住回谁。纯解释/短问答可省略。格式见 \`.harness/rules/core.md\` 铁律 9。"
        echo ""
        echo "## 角色协作"
        echo ""
        echo "需要需求评审、测试策略、代码审查时，用户会明确点名对应角色。"
        echo "角色文件见 \`.harness/rules/roles/\`（pm.md / qa.md / reviewer.md / designer.md）。"
        echo ""
        echo "## 详细规范"
        echo ""
        echo "完整 Playbook（Git / CI-CD / 测试 / Brain 记忆写入 / Plan-Execute Protocol）见 \`.harness/rules/extended.md\`。"
        echo "需要时主动读取该文件。"
    else
        echo "> 本项目使用 Mick Harness 单源规则体系。下面的「Mick Agent Kernel」是最高优先级，任何情况不可违反。"
        echo ""
        cat "$CORE"
        echo ""
        if [ "$profile" = "full" ]; then
            echo "---"
            echo ""
            cat "$EXTENDED"
        else
            echo "---"
            echo ""
            echo "## 详细规范"
            echo ""
            echo "完整 Playbook（代码质量 / Git / CI-CD / 测试 / 角色协作）见 \`.harness/rules/extended.md\`。"
            echo "需要时主动读取该文件，不要凭印象编造规范。"
        fi
    fi
}

# Default: one project entry. Use --all only for tools that cannot read AGENTS.md
# through a global loader.
TARGETS=(
    "AGENTS.md|lean|AGENTS.md 通用标准 (Codex / Zed / Aider)"
)

ALL_TARGETS=(
    "CLAUDE.md|lean|Claude Code"
    ".cursorrules|full|Cursor"
    ".windsurfrules|full|Windsurf"
    ".clinerules|full|Cline / Roo"
    ".github/copilot-instructions.md|lean|GitHub Copilot"
    ".trae/rules.md|lean|Trae"
)

mkdir -p "$DIST"

GENERATED=0
if [ "$GEN_ALL" = true ]; then
    TARGETS+=("${ALL_TARGETS[@]}")
elif [ "$CHECK_MODE" != true ]; then
    # Clean up stale multi-IDE files from previous --all runs
    for f in "CLAUDE.md" ".cursorrules" ".windsurfrules" ".clinerules" ".github/copilot-instructions.md" ".trae/rules.md"; do
        rm -f "$DIST/$f"
    done
    rm -rf "$DIST/.github" "$DIST/.trae" 2>/dev/null || true
fi

DRIFT=0

strip_capsule_block() {
    local file="$1"
    awk '
        /^<!-- =+ -->$/ { pending_banner=$0; next }
        pending_banner != "" && /Mick Agent Capsule/ {
            pending_banner=""
            in_capsule=1
            next
        }
        pending_banner != "" {
            print pending_banner
            pending_banner=""
        }
        /Mick Agent Capsule/ { in_capsule=1; next }
        in_capsule && /^---[[:space:]]*$/ { in_capsule=0; next }
        in_capsule { next }
        { print }
        END {
            if (pending_banner != "") print pending_banner
        }
    ' "$file"
}

generated_file_matches() {
    local expected="$1" actual="$2"
    local expected_body actual_body

    [ -f "$actual" ] || return 1
    if diff -q "$expected" "$actual" >/dev/null 2>&1; then
        return 0
    fi

    expected_body="$(mktemp)"
    actual_body="$(mktemp)"
    strip_capsule_block "$expected" > "$expected_body"
    strip_capsule_block "$actual" > "$actual_body"

    if diff -q "$expected_body" "$actual_body" >/dev/null 2>&1; then
        rm -f "$expected_body" "$actual_body"
        return 0
    fi

    rm -f "$expected_body" "$actual_body"
    return 1
}

for entry in "${TARGETS[@]}"; do
    IFS='|' read -r rel profile name <<< "$entry"
    out="$DIST/$rel"
    mkdir -p "$(dirname "$out")"
    tmp="$(mktemp)"
    render "$profile" "$name" > "$tmp"

    if [ "$CHECK_MODE" = true ]; then
        if ! generated_file_matches "$tmp" "$out"; then
            warn "Out of date: dist/$rel"
            ((DRIFT++))
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$out"
        ok "Generated: dist/$rel  [$profile]"
        ((GENERATED++))
    fi
done

echo ""
if [ "$CHECK_MODE" = true ]; then
    if [ "$DRIFT" -gt 0 ]; then
        fail "$DRIFT file(s) out of date. Run: .harness/generate.sh"
        exit 1
    fi
    ok "All generated rule files are up to date."
else
    ok "Generated $GENERATED rule files into dist/ from single source."
    info "setup.sh symlinks project-root rule files to these. Edit rules/*.md and re-run to propagate."
fi
