#!/bin/bash
set -euo pipefail

# ============================================================
# generate.sh — Single-source rule generator
#
# Reads the canonical source of truth:
#   rules/core.md      (the 10 non-negotiable rules — weak-model optimized)
#   rules/extended.md  (full engineering depth)
#
# Produces IDE/agent-specific rule files into dist/, each assembled
# under one of three profiles:
#   minimal → only project-specific constraints (Anthropic Claude 原生模型 in Claude Code)
#   lean    → core inline + pointer to extended (非原生模型 in Claude Code, AGENTS.md, Copilot, Trae)
#   full    → core + extended fully inline      (Cursor, Windsurf, Cline)
#
# setup.sh symlinks the project-root rule files to dist/<file>, so a
# single edit to core.md / extended.md propagates everywhere after
# re-running this script.
#
# Usage:
#   ./generate.sh            # regenerate all targets
#   ./generate.sh --check    # verify dist/ is up to date (CI guard), no writes
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}ℹ️  $1${NC}"; }
ok()    { echo -e "${GREEN}✅ $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠️  $1${NC}"; }
fail()  { echo -e "${RED}❌ $1${NC}"; }

HARNESS_ROOT="$(cd "$(dirname "$0")" && pwd)"
CORE="$HARNESS_ROOT/rules/core.md"
EXTENDED="$HARNESS_ROOT/rules/extended.md"
DIST="$HARNESS_ROOT/dist"

CHECK_MODE=false
[ "${1:-}" = "--check" ] && CHECK_MODE=true

for f in "$CORE" "$EXTENDED"; do
    if [ ! -f "$f" ]; then
        fail "Source of truth missing: $f"
        exit 1
    fi
done

# A short, machine-and-human readable "do not edit" banner.
banner() {
    cat <<EOF
<!-- ============================================================ -->
<!-- AUTO-GENERATED by .harness/generate.sh — DO NOT EDIT BY HAND -->
<!-- Edit the source of truth instead:                            -->
<!--   .harness/rules/core.md      (the 10 core rules)            -->
<!--   .harness/rules/extended.md  (full engineering rules)       -->
<!-- Then re-run: .harness/generate.sh                            -->
<!-- ============================================================ -->
EOF
}

# ----------------------------------------------------------------
# Constitution injection — pull Mick's iron laws from Brain (if available)
# If Brain doesn't exist (e.g. other users who cloned this harness),
# this function outputs nothing — clean engineering rules only.
# ----------------------------------------------------------------
constitution_inject() {
    local constitution="${HOME}/.mick-brain/constitution.md"
    local gotchas="${HOME}/.mick-brain/global/gotchas.md"

    if [ ! -f "$constitution" ]; then
        return 0
    fi

    cat <<'INJECT_HEADER'

<!-- ============================================================ -->
<!-- Mick Constitution 注入 — 个人铁律（从 Brain 自动拉取）      -->
<!-- 源文件: ~/.mick-brain/constitution.md                       -->
<!-- 其他人的机器上 Brain 不存在 → 本段静默跳过，纯工程规则      -->
<!-- ============================================================ -->

## ⚡ Mick 个人铁律（优先级最高，违反即违约）

> 以下 6 条在任何场景、任何模型、任何角色下都必须遵守。
> 完整协议见 `~/.mick-brain/constitution.md`。

0. **第一性原理** — 收到任何需求，先追问根本问题。禁止在根本问题被回答前讨论实现方案。
1. **对抗性审查** — 执行前站在对立面审查合理性。新功能 ≥3 质疑点，修改 ≥2，Bug ≥1。明知更好方案不提 = 失职。
2. **需求不膨胀** — 每次方案扩大时用剃刀："这个不加，用户能不能完成核心任务？"
3. **5 闸门推理** — A)边界定义 B)分支穷举(含"不做") C)证据标注[已知][推断][未验证][猜测] D)自校验轮 E)不懂就停。简单查询可跳过 B/D。
4. **反馈分级** — 质疑≠否定。🔵不确定→重新验证不翻转 🟡纠正→局部修正 🟠转向→盘点可复用 🟢范围→收缩粒度。
5. **自持续** — 踩坑/偏好/决策主动标注写入 Brain。同一错误 ≥2 次→触发熔断检查 gotchas。

INJECT_HEADER

    if [ -f "$gotchas" ]; then
        local recent
        recent=$(grep '^- \[' "$gotchas" 2>/dev/null | tail -5)
        if [ -n "$recent" ]; then
            echo ""
            echo "**⚠️ 最近踩坑（来自 Brain gotchas）**："
            echo "$recent"
        fi
    fi

    echo ""
    echo "---"
    echo ""
}

# Build one target file body to stdout.
#   $1 = profile (minimal|lean|full)
#   $2 = tool display name (for the intro line)
render() {
    local profile="$1" tool="$2"
    banner
    echo ""
    echo "# 工程规范 · $tool"
    echo ""
    constitution_inject

    if [ "$profile" = "minimal" ]; then
        # Minimal profile: only rules the tool DOESN'T enforce natively.
        # For strong models (Claude Code) that already have built-in:
        #   - read before edit, plan before act, ask when unclear
        #   - defensive coding, error analysis, self-review
        #   - permission system for dangerous ops
        echo "> 本项目使用 Mick Harness。你的内建能力已覆盖大部分编码规范，以下仅补充你不知道的项目级约束。"
        echo ""
        echo "## 项目级约束"
        echo ""
        echo "**⚡ 前置检查**：开始任何任务前，先看 \`plan.md\` 是否存在。存在则读取它，按其中的步骤逐一执行，每完成一步将 \`[ ]\` 改为 \`[x]\`。不存在则跳过本条，正常工作。"
        echo ""
        echo "**锁死技术栈**：不擅自更换语言/框架/库，不擅自引入新依赖。要换先说明原因并等用户确认。"
        echo ""
        echo "**回合卡片收尾**：每次回复结尾输出回合卡片——✅ 本回合做了什么 / 📍 整体进度 / ➡️ 下一步切到哪、粘贴什么 / 🆘 卡住回谁。多线程切换时靠它不失焦。格式见 \`.harness/rules/core.md\` 铁律 10。"
        echo ""
        echo "## 角色协作"
        echo ""
        echo "需要需求评审、测试策略、代码审查时，用户会明确点名对应角色。"
        echo "角色文件见 \`.harness/rules/roles/\`（pm.md / qa.md / reviewer.md / designer.md）。"
        echo ""
        echo "## 详细规范"
        echo ""
        echo "完整工程规范（Git / CI-CD / 测试 / Brain 记忆写入 / Plan-Execute Protocol）见 \`.harness/rules/extended.md\`。"
        echo "需要时主动读取该文件。"
    else
        echo "> 本项目使用 Mick Harness 单源规则体系。下面的「核心铁律」是最高优先级，任何情况不可违反。"
        echo ""
        cat "$CORE"
        echo ""
        echo "---"
        echo ""
        echo "## Executor 纪律（plan.md 存在时强制生效）"
        echo ""
        echo "当 \`plan.md\` 存在且含 \`- [ ]\` 未完成步骤时，你自动进入 **Executor 模式**，以下红线不可逾越："
        echo ""
        echo "1. **🚫 不做架构决策** — plan 没写的不发明。缺什么写 \`## 阻塞\` 停下，不硬猜。"
        echo "2. **🚫 不改 plan 的目标/约束/步骤/验收标准** — 你只能标完成 \`[x]\`、加执行备注、写沟通区。"
        echo "3. **🚫 不引入 plan 没列的依赖** — 只用 plan 里出现过的包/模块。"
        echo "4. **🚫 不"顺手优化"** — 不加 plan 没要求的缓存/重试/降级/抽象/清理。多做 = 越权。"
        echo "5. **🚫 不跳步** — 必须按顺序执行，不许并行或跳过。"
        echo "6. **🚫 不在 plan 范围外做额外改动** — 看到项目里有"脏数据/配置遗漏"不要自动清理，plan 决定你干什么。"
        echo "7. **✅ 遇到 plan 没说清的地方** → 停下写阻塞报告（带证据），不要自己猜实现。"
        echo "8. **✅ 完成后按结构化格式追加自检日志** — 每步必须有 \`### Step N\` + \`files:\` + \`verify:\` 行。\`harness-audit.sh\` 会自动扫描。"
        echo ""
        echo "违反以上任何一条 = 越权。完整 Executor 协议见 \`.harness/rules/roles/executor.md\` 和 \`extended.md\` §10.3。"
        echo ""
        if [ "$profile" = "full" ]; then
            echo "---"
            echo ""
            cat "$EXTENDED"
        else
            echo "---"
            echo ""
            echo "## 详细规范"
            echo ""
            echo "完整工程规范（代码哲学 / Git / CI-CD / 测试 / 角色协作）见 \`.harness/rules/extended.md\`。"
            echo "需要时主动读取该文件，不要凭印象编造规范。"
        fi
    fi
}

# target_path | profile | display name
TARGETS=(
    "AGENTS.md|lean|AGENTS.md 通用标准 (Codex / Zed / Aider)"
    "CLAUDE.md|lean|Claude Code"
    ".cursorrules|full|Cursor"
    ".windsurfrules|full|Windsurf"
    ".clinerules|full|Cline / Roo"
    ".github/copilot-instructions.md|lean|GitHub Copilot"
    ".trae/rules.md|lean|Trae"
)

mkdir -p "$DIST"

GENERATED=0
DRIFT=0
for entry in "${TARGETS[@]}"; do
    IFS='|' read -r rel profile name <<< "$entry"
    out="$DIST/$rel"
    mkdir -p "$(dirname "$out")"
    tmp="$(mktemp)"
    render "$profile" "$name" > "$tmp"

    if [ "$CHECK_MODE" = true ]; then
        if [ ! -f "$out" ] || ! diff -q "$tmp" "$out" >/dev/null 2>&1; then
            warn "Out of date: dist/$rel"
            ((DRIFT++))
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$out"
        ok "Generated: dist/$rel  [$profile]"
        ((GENERATED++))
    fi
done

echo ""
if [ "$CHECK_MODE" = true ]; then
    if [ "$DRIFT" -gt 0 ]; then
        fail "$DRIFT file(s) out of date. Run: .harness/generate.sh"
        exit 1
    fi
    ok "All generated rule files are up to date."
else
    ok "Generated $GENERATED rule files into dist/ from single source."
    info "setup.sh symlinks project-root rule files to these. Edit rules/*.md and re-run to propagate."
fi
