#!/bin/bash
set -euo pipefail

# ============================================================
# generate.sh — Single-source rule generator
#
# Reads the canonical source of truth:
#   rules/core.md      (the 10 non-negotiable rules — weak-model optimized)
#   rules/extended.md  (full engineering depth)
#
# Produces IDE/agent-specific rule files into dist/, each assembled
# under one of two profiles:
#   lean  → core inline + pointer to extended  (small context; weak models, AGENTS.md, Claude, Copilot, Trae)
#   full  → core + extended fully inline       (Cursor, Windsurf, Cline)
#
# setup.sh symlinks the project-root rule files to dist/<file>, so a
# single edit to core.md / extended.md propagates everywhere after
# re-running this script.
#
# Usage:
#   ./generate.sh            # regenerate all targets
#   ./generate.sh --check    # verify dist/ is up to date (CI guard), no writes
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}ℹ️  $1${NC}"; }
ok()    { echo -e "${GREEN}✅ $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠️  $1${NC}"; }
fail()  { echo -e "${RED}❌ $1${NC}"; }

HARNESS_ROOT="$(cd "$(dirname "$0")" && pwd)"
CORE="$HARNESS_ROOT/rules/core.md"
EXTENDED="$HARNESS_ROOT/rules/extended.md"
DIST="$HARNESS_ROOT/dist"

CHECK_MODE=false
[ "${1:-}" = "--check" ] && CHECK_MODE=true

for f in "$CORE" "$EXTENDED"; do
    if [ ! -f "$f" ]; then
        fail "Source of truth missing: $f"
        exit 1
    fi
done

# A short, machine-and-human readable "do not edit" banner.
banner() {
    cat <<EOF
<!-- ============================================================ -->
<!-- AUTO-GENERATED by .harness/generate.sh — DO NOT EDIT BY HAND -->
<!-- Edit the source of truth instead:                            -->
<!--   .harness/rules/core.md      (the 10 core rules)            -->
<!--   .harness/rules/extended.md  (full engineering rules)       -->
<!-- Then re-run: .harness/generate.sh                            -->
<!-- ============================================================ -->
EOF
}

# Build one target file body to stdout.
#   $1 = profile (lean|full)
#   $2 = tool display name (for the intro line)
render() {
    local profile="$1" tool="$2"
    banner
    echo ""
    echo "# 工程规范 · $tool"
    echo ""
    echo "> 本项目使用 Mick Harness 单源规则体系。下面的「核心铁律」是最高优先级，任何情况不可违反。"
    echo ""
    cat "$CORE"
    echo ""
    if [ "$profile" = "full" ]; then
        echo "---"
        echo ""
        cat "$EXTENDED"
    else
        echo "---"
        echo ""
        echo "## 详细规范"
        echo ""
        echo "完整工程规范（代码哲学 / Git / CI-CD / 测试 / 角色协作）见 \`.harness/rules/extended.md\`。"
        echo "需要时主动读取该文件，不要凭印象编造规范。"
    fi
}

# target_path | profile | display name
TARGETS=(
    "AGENTS.md|lean|AGENTS.md 通用标准 (Codex / Zed / Aider)"
    "CLAUDE.md|lean|Claude Code"
    ".cursorrules|full|Cursor"
    ".windsurfrules|full|Windsurf"
    ".clinerules|full|Cline / Roo"
    ".github/copilot-instructions.md|lean|GitHub Copilot"
    ".trae/rules.md|lean|Trae"
)

mkdir -p "$DIST"

GENERATED=0
DRIFT=0
for entry in "${TARGETS[@]}"; do
    IFS='|' read -r rel profile name <<< "$entry"
    out="$DIST/$rel"
    mkdir -p "$(dirname "$out")"
    tmp="$(mktemp)"
    render "$profile" "$name" > "$tmp"

    if [ "$CHECK_MODE" = true ]; then
        if [ ! -f "$out" ] || ! diff -q "$tmp" "$out" >/dev/null 2>&1; then
            warn "Out of date: dist/$rel"
            ((DRIFT++))
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$out"
        ok "Generated: dist/$rel  [$profile]"
        ((GENERATED++))
    fi
done

echo ""
if [ "$CHECK_MODE" = true ]; then
    if [ "$DRIFT" -gt 0 ]; then
        fail "$DRIFT file(s) out of date. Run: .harness/generate.sh"
        exit 1
    fi
    ok "All generated rule files are up to date."
else
    ok "Generated $GENERATED rule files into dist/ from single source."
    info "setup.sh symlinks project-root rule files to these. Edit rules/*.md and re-run to propagate."
fi
